// ============================================================
// FLORESCO — Product Catalogue (seed data & client-side demo)
// ============================================================
export const PRODUCTS_DATA = [
  {
    slug: 'velvet-oud-intense',
    name: 'Velvet Oud Intense',
    brand: 'House Niche',
    category: 'arabian-oud' as const,
    tagline: 'Deep, smoky oud with warm amber and damask rose.',
    description: 'A masterful composition that unfolds like a velvet curtain in a candlelit room. Rare Cambodian oud meets damask rose and golden amber at the heart, finishing with sandalwood and white musk that lingers for hours. This is not a fragrance you wear — it is one you inhabit.',
    scentNotes: { top: ['Bergamot', 'Saffron', 'Pink Pepper'], heart: ['Damask Rose', 'Amber', 'Jasmine'], base: ['Cambodian Oud', 'Sandalwood', 'White Musk'] },
    sizes: [{ size: '50ml', price: 8500, stock: 12, sku: 'VOI-50' }, { size: '100ml', price: 14500, stock: 8, sku: 'VOI-100' }],
    images: [{ url: '', alt: 'Velvet Oud Intense 50ml', isPrimary: true }],
    color1: '#3A2C22', color2: '#7A5A38',
    featured: true, badge: 'Bestseller', rating: 4.9, reviewCount: 128,
    seo: { metaTitle: 'Velvet Oud Intense | Floresco', metaDescription: 'Deep Cambodian oud with damask rose and amber. The signature of the house.' },
  },
  {
    slug: 'bloom-de-nuit',
    name: 'Bloom de Nuit',
    brand: 'Designer',
    category: 'women' as const,
    tagline: 'Night-blooming florals wrapped in creamy vanilla.',
    description: 'A luminous white floral that opens with bergamot and pink pepper before unfolding into jasmine sambac and tuberose in full bloom. Grounded by creamy vanilla and Australian sandalwood for an intimacy that lasts from evening into the next morning.',
    scentNotes: { top: ['Bergamot', 'Pink Pepper', 'Mandarin'], heart: ['Jasmine Sambac', 'Tuberose', 'White Peony'], base: ['Vanilla', 'Sandalwood', 'White Musk'] },
    sizes: [{ size: '30ml', price: 8200, stock: 6, sku: 'BDN-30' }, { size: '50ml', price: 12800, stock: 15, sku: 'BDN-50' }, { size: '100ml', price: 18500, stock: 7, sku: 'BDN-100' }],
    images: [{ url: '', alt: 'Bloom de Nuit', isPrimary: true }],
    color1: '#C77B95', color2: '#EFC2D0',
    featured: true, badge: 'New', rating: 4.8, reviewCount: 94,
    seo: { metaTitle: 'Bloom de Nuit | Floresco', metaDescription: 'A night-blooming floral with jasmine and vanilla.' },
  },
  {
    slug: 'noir-elegant-homme',
    name: 'Noir Élégant Homme',
    brand: 'Designer',
    category: 'men' as const,
    tagline: 'Lavender and iris with tonka and aged leather.',
    description: 'Structured, confident, and utterly timeless. Lavender absolute meets iris and tonka bean for a composition that reads as quietly powerful — the olfactory equivalent of a perfectly tailored suit. Built for evening, remembered forever.',
    scentNotes: { top: ['Lavender', 'Cardamom', 'Bergamot'], heart: ['Iris', 'Geranium', 'Sage'], base: ['Tonka Bean', 'Leather', 'Vetiver'] },
    sizes: [{ size: '50ml', price: 11200, stock: 10, sku: 'NEH-50' }, { size: '100ml', price: 15800, stock: 5, sku: 'NEH-100' }],
    images: [{ url: '', alt: 'Noir Élégant Homme', isPrimary: true }],
    color1: '#222226', color2: '#5B5B66',
    featured: true, rating: 4.7, reviewCount: 76,
    seo: { metaTitle: 'Noir Élégant Homme | Floresco', metaDescription: 'A structured masculine fragrance of lavender, iris, and tonka.' },
  },
  {
    slug: 'rose-damascena',
    name: 'Rose Damascena',
    brand: 'Arabian House',
    category: 'arabian-oud' as const,
    tagline: 'Turkish rose absolute with honey and white musk.',
    description: 'A love letter to the world\'s most prized rose. Distilled flowers from the rose valley of Isparta meet golden honey and soft animalic musk for a fragrance that is simultaneously delicate and powerful — exactly like the people who wear it.',
    scentNotes: { top: ['Damask Rose', 'Lychee', 'Bergamot'], heart: ['Rose Absolute', 'Honey', 'Peony'], base: ['White Musk', 'Sandalwood', 'Patchouli'] },
    sizes: [{ size: '50ml', price: 7200, stock: 20, sku: 'RD-50' }, { size: '100ml', price: 12500, stock: 14, sku: 'RD-100' }],
    images: [{ url: '', alt: 'Rose Damascena', isPrimary: true }],
    color1: '#8E2C48', color2: '#D66E8C',
    featured: true, rating: 4.9, reviewCount: 156,
    seo: { metaTitle: 'Rose Damascena | Floresco', metaDescription: 'Turkish rose absolute with honey and white musk.' },
  },
  {
    slug: 'sauvage-moderne',
    name: 'Sauvage Moderne EDP',
    brand: 'Designer',
    category: 'men' as const,
    tagline: 'Bergamot, Sichuan pepper and radiant ambroxan.',
    description: 'A modern classic reinterpreted with greater depth. Reggio bergamot and Sichuan pepper at the top give way to elemi and nutmeg at the heart, finishing with an ambroxan base of extraordinary radiance — clean without being empty.',
    scentNotes: { top: ['Bergamot', 'Sichuan Pepper', 'Lavender'], heart: ['Elemi', 'Nutmeg', 'Ambroxan'], base: ['Ambroxan', 'Cedar', 'Labdanum'] },
    sizes: [{ size: '60ml', price: 12500, stock: 8, sku: 'SM-60' }, { size: '100ml', price: 16800, stock: 6, sku: 'SM-100' }],
    images: [{ url: '', alt: 'Sauvage Moderne EDP', isPrimary: true }],
    color1: '#1B2B45', color2: '#4A6FA5',
    featured: false, rating: 4.8, reviewCount: 203,
    seo: { metaTitle: 'Sauvage Moderne EDP | Floresco', metaDescription: 'Bergamot and ambroxan — a modern masculine icon.' },
  },
  {
    slug: 'mademoiselle-cherie',
    name: 'Mademoiselle Chérie',
    brand: 'Designer',
    category: 'women' as const,
    tagline: 'Orange blossom, May rose and soft patchouli.',
    description: 'Effortlessly chic. Sicilian orange blossom sparkles over a heart of May rose and Grasse jasmine, resting on a bed of soft patchouli and white musk. This is the scent of confidence worn lightly — the woman who needs no introduction.',
    scentNotes: { top: ['Sicilian Orange', 'Neroli', 'Mandarin'], heart: ['May Rose', 'Grasse Jasmine', 'Iris'], base: ['Patchouli', 'White Musk', 'Vetiver'] },
    sizes: [{ size: '35ml', price: 11800, stock: 9, sku: 'MC-35' }, { size: '50ml', price: 15800, stock: 12, sku: 'MC-50' }, { size: '100ml', price: 22000, stock: 4, sku: 'MC-100' }],
    images: [{ url: '', alt: 'Mademoiselle Chérie', isPrimary: true }],
    color1: '#A8323E', color2: '#E8909A',
    featured: false, badge: "Editor's Pick", rating: 4.9, reviewCount: 187,
    seo: { metaTitle: 'Mademoiselle Chérie | Floresco', metaDescription: 'Orange blossom and rose — effortless chic.' },
  },
  {
    slug: 'amber-royale',
    name: 'Amber Royale',
    brand: 'House Niche',
    category: 'unisex' as const,
    tagline: 'Golden amber, saffron and Atlas cedar.',
    description: 'Regal, enveloping, uncompromising. Golden amber meets Persian saffron and Moroccan cedar for a fragrance as luxurious as a silk robe by firelight. Thoroughly unisex — this belongs to whoever has the courage to wear it.',
    scentNotes: { top: ['Saffron', 'Bergamot', 'Cardamom'], heart: ['Amber', 'Rose', 'Iris'], base: ['Atlas Cedar', 'Sandalwood', 'Amber Resin'] },
    sizes: [{ size: '50ml', price: 9800, stock: 11, sku: 'AR-50' }, { size: '100ml', price: 14200, stock: 7, sku: 'AR-100' }],
    images: [{ url: '', alt: 'Amber Royale', isPrimary: true }],
    color1: '#8A5A1E', color2: '#D9A84E',
    featured: false, rating: 4.7, reviewCount: 91,
    seo: { metaTitle: 'Amber Royale | Floresco', metaDescription: 'Golden amber and saffron — unisex luxury.' },
  },
  {
    slug: 'citrus-verde',
    name: 'Citrus Verde',
    brand: 'House Niche',
    category: 'unisex' as const,
    tagline: 'Sicilian lime, green tea and earthy vetiver.',
    description: 'The scent of a Mediterranean morning distilled in glass. Bright Sicilian lime and mint over green tea and basil, grounded by earthy vetiver and cedar. Fresh without being fleeting — built for the Kenyan heat.',
    scentNotes: { top: ['Sicilian Lime', 'Mint', 'Grapefruit'], heart: ['Green Tea', 'Basil', 'Petitgrain'], base: ['Vetiver', 'Cedar', 'Musk'] },
    sizes: [{ size: '50ml', price: 6900, stock: 18, sku: 'CV-50' }, { size: '100ml', price: 10500, stock: 12, sku: 'CV-100' }],
    images: [{ url: '', alt: 'Citrus Verde', isPrimary: true }],
    color1: '#2E5D3A', color2: '#7FB77E',
    featured: false, badge: 'Fresh Pick', rating: 4.6, reviewCount: 63,
    seo: { metaTitle: 'Citrus Verde | Floresco', metaDescription: 'Lime, green tea and vetiver — a fresh unisex fragrance.' },
  },
  {
    slug: 'oud-malaki',
    name: 'Oud Malaki',
    brand: 'Arabian House',
    category: 'arabian-oud' as const,
    tagline: 'Aged Cambodian oud with leather and warming spice.',
    description: 'Uncompromising and majestic. Aged Cambodian oud takes undisputed center stage, supported by soft leather and warming spices that unfold slowly across the skin. For those who understand the language of oud — and speak it fluently.',
    scentNotes: { top: ['Smoky Oud', 'Cardamom', 'Cinnamon'], heart: ['Damask Rose', 'Leather', 'Incense'], base: ['Aged Oud', 'Sandalwood', 'Amber'] },
    sizes: [{ size: '30ml', price: 8400, stock: 6, sku: 'OM-30' }, { size: '50ml', price: 12500, stock: 4, sku: 'OM-50' }],
    images: [{ url: '', alt: 'Oud Malaki', isPrimary: true }],
    color1: '#2B1F1A', color2: '#6E4A2F',
    featured: false, rating: 4.9, reviewCount: 74,
    seo: { metaTitle: 'Oud Malaki | Floresco', metaDescription: 'Aged Cambodian oud — royal and uncompromising.' },
  },
  {
    slug: 'aqua-marine-homme',
    name: 'Aqua Marine Homme',
    brand: 'Designer',
    category: 'men' as const,
    tagline: 'Sea accord, neroli and clean white musk.',
    description: 'The freshness of an ocean breeze bottled. Marine accord, neroli and mint create an instantly invigorating opening that softens into white musk and driftwood for a signature that is both energising and sophisticated.',
    scentNotes: { top: ['Sea Notes', 'Mint', 'Bergamot'], heart: ['Neroli', 'Lavender', 'Marine'], base: ['White Musk', 'Cedar', 'Driftwood'] },
    sizes: [{ size: '50ml', price: 8500, stock: 14, sku: 'AMH-50' }, { size: '100ml', price: 12200, stock: 8, sku: 'AMH-100' }],
    images: [{ url: '', alt: 'Aqua Marine Homme', isPrimary: true }],
    color1: '#0E4C63', color2: '#57B3C9',
    featured: false, rating: 4.5, reviewCount: 112,
    seo: { metaTitle: 'Aqua Marine Homme | Floresco', metaDescription: 'Marine freshness — sea, neroli and clean musk.' },
  },
  {
    slug: 'fleur-divoire',
    name: "Fleur d'Ivoire",
    brand: 'House Niche',
    category: 'women' as const,
    tagline: 'Peony, lychee and cashmeran musk.',
    description: 'Soft, radiant, unmistakably feminine. Peonies just cut from a spring garden, a whisper of lychee, and skin-warm cashmeran musk. The fragrance of the person you aspire to be and already are.',
    scentNotes: { top: ['Peony', 'Lychee', 'Freesia'], heart: ['Rose', 'Magnolia', 'Jasmine'], base: ['Cashmeran', 'White Musk', 'Cedar'] },
    sizes: [{ size: '50ml', price: 8800, stock: 16, sku: 'FDI-50' }, { size: '100ml', price: 13500, stock: 9, sku: 'FDI-100' }],
    images: [{ url: '', alt: "Fleur d'Ivoire", isPrimary: true }],
    color1: '#B08D3C', color2: '#EBD9A8',
    featured: false, rating: 4.8, reviewCount: 128,
    seo: { metaTitle: "Fleur d'Ivoire | Floresco", metaDescription: 'Peony, lychee and musk — softly radiant.' },
  },
  {
    slug: 'santal-mystique',
    name: 'Santal Mystique',
    brand: 'House Niche',
    category: 'unisex' as const,
    tagline: 'Australian sandalwood, cardamom and papyrus.',
    description: 'Meditative, warm, and quietly profound. Australian sandalwood at the heart wrapped in green cardamom and dry papyrus — a fragrance that feels like a temple at dusk. The kind of scent that makes people stop and turn.',
    scentNotes: { top: ['Cardamom', 'Papyrus', 'Bergamot'], heart: ['Sandalwood', 'Iris', 'Violet'], base: ['Sandalwood', 'Cedar', 'Amber'] },
    sizes: [{ size: '50ml', price: 11200, stock: 13, sku: 'SM2-50' }, { size: '100ml', price: 16500, stock: 6, sku: 'SM2-100' }],
    images: [{ url: '', alt: 'Santal Mystique', isPrimary: true }],
    color1: '#6B4A2E', color2: '#C29B6C',
    featured: false, badge: 'Staff Pick', rating: 4.8, reviewCount: 89,
    seo: { metaTitle: 'Santal Mystique | Floresco', metaDescription: 'Australian sandalwood and cardamom — meditative and warm.' },
  },
];
