// Merges this project's generated bindings/env vars (worker-configuration.d.ts,
// regenerated by `wrangler types` whenever wrangler.jsonc changes) into
// @opennextjs/cloudflare's `CloudflareEnv` interface, which getCloudflareContext()
// returns. Kept in a separate file since worker-configuration.d.ts is overwritten
// on every regeneration.
declare global {
  interface CloudflareEnv extends Env {}
}

export {};
