/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7f9225bdbce784625f59214691d9a81c)
interface __BaseEnv_Env {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	MONGODB_URI: string;
	AUTH_SECRET: string;
	NEXTAUTH_URL: string;
	MPESA_ENVIRONMENT: string;
	MPESA_CONSUMER_KEY: string;
	MPESA_CONSUMER_SECRET: string;
	MPESA_SHORTCODE: string;
	MPESA_PASSKEY: string;
	MPESA_CALLBACK_URL: string;
	FLW_PUBLIC_KEY: string;
	FLW_SECRET_KEY: string;
	FLW_ENCRYPTION_KEY: string;
	WHATSAPP_TOKEN: string;
	WHATSAPP_PHONE_NUMBER_ID: string;
	WHATSAPP_BUSINESS_ACCOUNT_ID: string;
	WHATSAPP_VERIFY_TOKEN: string;
	RESEND_API_KEY: string;
	EMAIL_FROM: string;
	CLOUDINARY_CLOUD_NAME: string;
	CLOUDINARY_API_KEY: string;
	CLOUDINARY_API_SECRET: string;
	R2_ACCOUNT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_BUCKET: string;
	R2_PUBLIC_URL: string;
	BUSINESS_NAME: string;
	BUSINESS_EMAIL: string;
	BUSINESS_PHONE: string;
	BUSINESS_ADDRESS: string;
	NEXT_PUBLIC_SITE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MONGODB_URI" | "AUTH_SECRET" | "NEXTAUTH_URL" | "MPESA_ENVIRONMENT" | "MPESA_CONSUMER_KEY" | "MPESA_CONSUMER_SECRET" | "MPESA_SHORTCODE" | "MPESA_PASSKEY" | "MPESA_CALLBACK_URL" | "FLW_PUBLIC_KEY" | "FLW_SECRET_KEY" | "FLW_ENCRYPTION_KEY" | "WHATSAPP_TOKEN" | "WHATSAPP_PHONE_NUMBER_ID" | "WHATSAPP_BUSINESS_ACCOUNT_ID" | "WHATSAPP_VERIFY_TOKEN" | "RESEND_API_KEY" | "EMAIL_FROM" | "CLOUDINARY_CLOUD_NAME" | "CLOUDINARY_API_KEY" | "CLOUDINARY_API_SECRET" | "R2_ACCOUNT_ID" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "R2_BUCKET" | "R2_PUBLIC_URL" | "BUSINESS_NAME" | "BUSINESS_EMAIL" | "BUSINESS_PHONE" | "BUSINESS_ADDRESS" | "NEXT_PUBLIC_SITE_URL">> {}
}
